
intro_list= [
  "Hi there, sir looking forward to see you",
  "Greetings sir, welcome back",
  "Hey There, what took you so long,i was waiting for you",
  "How’s everything going sir? ",
  "Good to see you sir, you look amazeing today",
  "Great to see you. i hope you are having a nice day sir",
  "Nice to see you sir ",
  "where have you been sir?",
  "Nice to see you again sir",
  "How are you holding up?",
  "Sir it’s been a while!",
  "This may be recorded for training purpose",
  "At least, we meet for the first time for the last time!",
  "It’s a Pleasure to Meet You sir",
  "How are you feeling today sir?",
  "Welcome back sir",
  "Hi, mister! What is going on?",
  "Top of the morning to ya! Wass es going on?",
  "Hello-hello! Who’s there? It’s me sofia talking",
  "Knock knock…who is there? It’s me, sofia!",
  "What’s up with you, old soul? Wanna chat?",
  "Welcome to the club, boss!",
  "Hey mistaa, how do you do?",
  "What’s new? Tell me everything!",
  "Namaste! How long has it been, dost?",
  "Hey Einstein, still cracking the old theory?",
  "What’s smokin’? Tell me everything!",
  "Hey sir! What’s the latest buzz in your world?",
]

morning_data=[
  "Let the morning dewdrops that wash away the burdens of yesterday. May god sprinkle much of these on you today! Good morning!",
  "Enjoy life – now! Good morning",
  "Give your day meaning by setting a goal. Then, work towards achieving that goal. Wishing you a very good morning!",
  "Wishing you a day full of sunny smiles and happy thoughts. Good morning!",
  "This is not just another day. It is yet another chance to make your dreams come true. Get up and get started. Good morning!",
  "You cannot change yesterday, you cannot predict tomorrow. Today is the only gift you have. That is why we call it the “present”. Have a good day!",
  "The chirping birds, the morning bells, the clear blue skies, new things to tell. Morning is here! Have a wonderful one!",
  "Sunshine is the best medicine. Here’s to a fresh start on this gorgeous new day!",
  "Seize the day with all your might, as you awaken from a peaceful night. Take on life’s challenges with a confident heart, for each day is a brand new start. Good morning!",
  "May this day bring new opportunities and successes for you. Good morning!",
  "Happy thoughts are the only cure for a sleepy morning…I feel the happiest when I think about you. Happy morning!",
  "Yesterday is miles away, and today is a new today. With new goals to meet, let’s rise and jump to our feet. Good Morning!",
  "It’s a new day! Add in the positive thoughts, subtract out the negative energy. Make it all equal to one fantastic day!",
  "It’s a brand new morning! The day is a blank canvas yet to be painted with the colors of life. Seize the day! Good morning!",
  "You are the secret ingredient to my happy day. Rise and shine, cutie!",
  "A little hello and lots of love to start your day. Have a beautiful morning and an amazing day ahead. ",
  "Growing old with you is my dream destination, Glorifying morning to my living world!",
  "You are my shining light. Now, it’s time to wake up and show the world your magic!",
  "Just the thought of you brightens up my morning. Good morning!",
  "Just like how a beautiful morning is incomplete without its orange hue, my morning is incomplete without texting you. Good morning!",
  " Good morning, sir. Here is my morning tip: you need no makeup. You will be messing with perfection. Love you!",
  "If it were up to me to rearrange the alphabets, I would keep U & I together. Good Morning!",
  "Begin this day with a cup full of positive thoughts, a spoonful of energy, and a jar full of love. Have a beautiful day. Good morning!",
  "You know that moment when you wake up in the morning rejuvenated and full of energy? Yeah, me neither.",
  "I could totally be a morning person. Only if mornings happened at noon. Good morning!",
  "Have you seen my reason for waking up in the morning? Oh, there you are!",
  "I believe there should be a better way to start each day – instead of waking up every morning",
  "As the day begins, remember that I am your friend…you’re welcome!",
  "Someday, you will be a morning person! But, not today. Go back to sleep!"
]
afternoon_data =[
  "Have a good afternoon and a great day! sir",
  "I am always thinking about you. Have a great afternoon sir",
  "You are as bright as the afternoon sun",
  "The afternoon is when the day starts to slow down. Enjoy yourself!",
  "Enjoy this time of day and the blessings that it brings. ",
  "Here’s a wish for a fun afternoon and the gentle breeze that comes with it",
  "Half of the day is over; have a marvelous afternoon and enjoy the rest of the day! ",
  "Good morning, afternoon, evening, and night. The day is more complete with you.",
  "May this afternoon bring you delightful surprises.",
  "Wishing you a happy day and a fabulous afternoon!",
  "May this beautiful afternoon fill your heart with happiness!",
  "I can only wish you all the best all day long.",
  "Today, there will be a beautiful sunset after you have a good afternoon!",
  "I would like to wish you a good afternoon and an even better evening ",
  "May your afternoon be filled with light, love, and happiness.",
  "Leave me a smile just warm enough to spend a million golden afternoons in."
  "Under certain circumstances there are few hours in life more agreeable than the hour dedicated to the ceremony known as afternoon tea",
  "Be bright like the afternoon sun and let everyone who sees you feel inspired by all the great things you do. You have one life here on earth. Make it count in whatever way you can.",
  "You could get a simple idea one afternoon that could completely change your life. Great innovators just needed one idea to change everything. Keep striving and you will reach success. ",
  "I’m never any good in the morning. It is only after four in the afternoon that I get going"

]



