from sofia_utils import *
intro_list= [
  "Hi there, sir looking forward to see you",
  "Greetings sir, welcome back",
  "Hey There, what took you so long,i was waiting for you",
  "How’s everything going sir? ",
  "Good to see you sir, you look amazeing today",
  "Great to see you. i hope you are having a nice day sir",
  "Nice to see you sir ",
  "where have you been sir?",
  "Nice to see you again sir",
  "How are you holding up?",
  "Sir it’s been a while!",
  "This may be recorded for training purpose",
  "At least, we meet for the first time for the last time!",
  "It’s a Pleasure to Meet You sir",
  "How are you feeling today sir?",
  "Welcome back sir",
  "Hi, mister! What is going on?",
  "Top of the "+ time() +" to you! What's going on?",
  "Hello-hello! Who’s there? It’s me sofia talking",
  "Knock knock…who is there? It’s me, sofia!",
  "What’s up with you, old soul? Wanna chat?",
  "Welcome to the club, boss!",
  "Hey mister, how do you do?",
  "Hey Einstein, still cracking the old theory?",
  "What’s smokin’? Tell me everything!",
  "Hey sir! What’s the latest buzz in your world?",
]

morning_data=[
  "Let the morning dewdrops that wash away the burdens of yesterday. May god sprinkle much of these on you today! Good morning!",
  "Enjoy life – now! Good morning",
  "Give your day meaning by setting a goal. Then, work towards achieving that goal. Wishing you a very good morning!",
  "Wishing you a day full of sunny smiles and happy thoughts. Good morning!",
  "This is not just another day. It is yet another chance to make your dreams come true. Get up and get started. Good morning!",
  "You cannot change yesterday, you cannot predict tomorrow. Today is the only gift you have. That is why we call it the “present”. Have a good day!",
  "The chirping birds, the morning bells, the clear blue skies, new things to tell. Morning is here! Have a wonderful one!",
  "Sunshine is the best medicine. Here’s to a fresh start on this gorgeous new day!",
  "Seize the day with all your might, as you awaken from a peaceful night. Take on life’s challenges with a confident heart, for each day is a brand new start. Good morning!",
  "May this day bring new opportunities and successes for you. Good morning!",
  "Happy thoughts are the only cure for a sleepy morning…I feel the happiest when I think about you. Happy morning!",
  "Yesterday is miles away, and today is a new today. With new goals to meet, let’s rise and jump to our feet. Good Morning!",
  "It’s a new day! Add in the positive thoughts, subtract out the negative energy. Make it all equal to one fantastic day!",
  "It’s a brand new morning! The day is a blank canvas yet to be painted with the colors of life. Seize the day! Good morning!",
  "You are the secret ingredient to my happy day. Rise and shine, cutie!",
  "A little hello and lots of love to start your day. Have a beautiful morning and an amazing day ahead. ",
  "Growing old with you is my dream destination, Glorifying morning to my living world!",
  "You are my shining light. Now, it’s time to wake up and show the world your magic!",
  "Just the thought of you brightens up my morning. Good morning!",
  "Just like how a beautiful morning is incomplete without its orange hue, my morning is incomplete without texting you. Good morning!",
  " Good morning, sir. Here is my morning tip: you need no makeup. You will be messing with perfection. Love you!",
  "If it were up to me to rearrange the alphabets, I would keep U & I together. Good Morning!",
  "Begin this day with a cup full of positive thoughts, a spoonful of energy, and a jar full of love. Have a beautiful day. Good morning!",
  "You know that moment when you wake up in the morning rejuvenated and full of energy? Yeah, me neither.",
  "I could totally be a morning person. Only if mornings happened at noon. Good morning!",
  "Have you seen my reason for waking up in the morning? Oh, there you are!",
  "I believe there should be a better way to start each day – instead of waking up every morning",
  "As the day begins, remember that I am your friend…you’re welcome!",
  "Someday, you will be a morning person! But, not today. Go back to sleep!"
]

afternoon_data =[
  "Have a good afternoon and a great day! sir",
  "I am always thinking about you. Have a great afternoon sir",
  "You are as bright as the afternoon sun",
  "The afternoon is when the day starts to slow down. Enjoy yourself!",
  "Enjoy this time of day and the blessings that it brings. ",
  "Here’s a wish for a fun afternoon and the gentle breeze that comes with it",
  "Half of the day is over; have a marvelous afternoon and enjoy the rest of the day! ",
  "Good morning, afternoon, evening, and night. The day is more complete with you.",
  "May this afternoon bring you delightful surprises.",
  "Wishing you a happy day and a fabulous afternoon!",
  "May this beautiful afternoon fill your heart with happiness!",
  "I can only wish you all the best all day long.",
  "Today, there will be a beautiful sunset after you have a good afternoon!",
  "I would like to wish you a good afternoon and an even better evening ",
  "May your afternoon be filled with light, love, and happiness.",
  "Leave me a smile just warm enough to spend a million golden afternoons in."
  "Under certain circumstances there are few hours in life more agreeable than the hour dedicated to the ceremony known as afternoon tea",
  "Be bright like the afternoon sun and let everyone who sees you feel inspired by all the great things you do. You have one life here on earth. Make it count in whatever way you can.",
  "You could get a simple idea one afternoon that could completely change your life. Great innovators just needed one idea to change everything. Keep striving and you will reach success. ",
  "I’m never any good in the morning. It is only after four in the afternoon that I get going"
]

evening_data = [
  "Good evening! I hope you had a good and productive day.",
  "No matter how bad your day has been, the beauty of the setting sun will make everything serene. Good evening.",
  "May the setting sun take down all your sufferings with it and make you hopeful for a new day. Good evening!",
  "It doesn’t matter how hectic your day was, you can’t help admiring the beauty of this evening. I hope you are having a good time right now! Good evening!",
  "Whether your day was good or bad, it has come to an end. Good evening and good luck for tomorrow.",
  "Evening is a good time to look back at your day and think about all the things that you have done. Enjoy your evening with positive thoughts.",
  "Happiness can’t be behind sorrow, It is your choice to make a better tomorrow, Enjoy this beautiful day with a lovely smile, Good evening!",
  "Evenings are your chance to forget the mistakes you made during the day, so for the sweetest of dreams, you can have the way. Good evening!",
  "Evening is a good time to look back at the day and think about all the good things you have done. I wish you an evening so full of satisfaction and inspiration",
  "Good evening my friend, take a sip of your coffee and forget the troubles of the day.",
  "It’s a perfect time to get rid of your worries and make yourself prepared for what’s coming tomorrow. Make this evening the beginning of a wonderful journey.",
  "The sun sets every evening with a promise to rise up once again at every dawn. Evenings are so full of hope and inspiration. Wishing you a very wonderful evening!",
  "Look at the sunset and then smile, Look at the horizon and smile, Enjoy this beautiful evening today, And have a nice time, Good evening to you!",
  "I hope you are having a refreshing evening as I am having here thinking of you. Good evening, sir",
  "Sometimes the best thing you can do is not think no wonder, not imagine and not obsess. Just breathe and have faith that everything will work out for the best. Good evening!",
  "Evening is the time for peace, Where there is no tension to cease, On this evening, I want to wish you, That you have a good evening!",
  "I know today was hard for you but I also know that tomorrow will come with new hopes and aspirations. Good evening sir, keep fighting.",
  "You don’t need beautiful weather to enjoy this evening. What you need is to kill a lot of mosquitoes so I can relax and have my coffee in peace! Good evening!",
  "Evening is special Not because it is the coolest time of the day, But, it lets you reflect on your day and forget your yesterday, Good evening!",
  "Evenings are always full of motivations and a new chance to look forward to the good times. So, never waste it sir. Have a warm evening.",
  "The evening’s the best part of the day. You’ve done your day’s work. Now you can put your feet up and enjoy it",
  "Come in the evening, or come in the morning; Come when you’re looked for, or come without warning",
  "Stop stressing about your sore day and enjoy the cool breeze of the fascinating evening. Eat lots of good food and cherish your evening well. Have a great time, sir",
  "Follow the rhythm of your heart, Heart takes you to the destination, Where your goodness dwells, Have a happy evening",
  "",
]

voice_error = [
  "Sorry, I didn’t understand. Could you say that again, please? ",
  "Sorry, I didn’t catch that. Could you repeat a little louder, please? ",
  "I don’t know that word, could you please tell me what it means?",
  "I can’t hear you very well. Could you speak up, please? ",
  "Sorry, English is not my first language. Would you mind repeating that once more?",
  "Sorry, my English is not that great. Would you mind speaking more slowly?",
  "Sorry, I’m afraid I don’t follow you.",
  "Excuse me, could you repeat once more",
  "I’m sorry, I don’t understand. Could you say it again?",
  "I’m sorry, I didn’t catch that. Would you mind speaking more slowly?",
  "I’m confused. Could you tell me again?",
  "I’m sorry, I didn’t understand. Could you repeat a little louder, please?",
  "I didn’t hear you. Please could you tell me again?",
  "I can’t make head nor tail of what you’re saying.can you please tell me more spacific",
  "Sorry i did not hear your voice properly. can you please repeat it again ",
]